### ISSUE TITLE
Warning: stringop-truncation on gcc release build

### ISSUE THREAD

**Issue by hsandt** [gpakosz/Assert#12]
I got this warning when building with gcc for release (not debug, not with clang):

```
In file included from /usr/include/string.h:494,
                 from /usr/include/c++/10/cstring:42,
                 from ../engine/third-party/PPK_ASSERT/src/ppk_assert.cpp:13:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘ppk::assert::AssertionException& ppk::assert::AssertionException::operator=(const ppk::assert::AssertionException&)’ at ../engine/third-party/PPK_ASSERT/src/ppk_assert.cpp:386:16:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncatio]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../engine/third-party/PPK_ASSERT/src/ppk_assert.cpp: In member function ‘ppk::assert::AssertionException& ppk::assert::AssertionException::operator=(const ppk::assert::AssertionException&)’:
../engine/third-party/PPK_ASSERT/src/ppk_assert.cpp:351:27: note: length computed here
  351 |     size_t length = strlen(message);
      |                     ~~~~~~^~~~~~~~~
```

Note that I enabled warnings as errors, so this prevents compilation for me, but otherwise it would just be a warning.

I found this thread https://stackoverflow.com/questions/65127257/gcc-strncat-output-may-be-truncated-werror-stringop-truncation-what-does suggesting to use memcpy, but since I don't want to modify third-party code and I want to keep all warnings as errors, I just disabled the stringop-truncation entirely (note it's written as "stringop-truncatio" in the message above).

I personally prefer the more semantical strncpy, so I would understand if you didn't want to use memcpy or use some other tricks to remove the warning. Of course, if you have a clean solution, just go ahead. I looked at the code and the lengths seem correct, but as length is computed dynamically, the compiler may not recognize that.

Even if you don't change your code, I put this issue here so people having the same problem know about some solutions.

**Comment by gpakosz** [comment]
Hello @hsandt 👋

Can you please try the `gh-12` branch?

**Comment by hsandt** [comment]
Thanks, I'll try it next time (hopefully tomorrow), after re-enabling the warnings.

**Comment by gpakosz** [comment]
Got a chance to try?

**Comment by hsandt** [comment]
Yes it's working now!
