### ISSUE TITLE
[docs] what are PPK_ASSERT_FUNCSPEC and PPK_ASSERT_CALL for?

### ISSUE THREAD

**Issue by onqtam** [gpakosz/Assert#7]
my guess is - if I want to build ppk_assert as a .dll?

Thanks for the great project!

And a side question - would it be possible to remove as much as possible from the source file if ```PPK_ASSERT_ENABLED``` is 0? I don't want to rely on link-time optimizations to remove dead code.

And one more note: Since C++11 local static variables are required to have synchronization added by the compiler for their initialization - so calling the function from multiple threads is safe. This may add A LOT of overhead if asserts are used on hot paths... Maybe this should be mentioned near ```PPK_ASSERT_DISABLE_IGNORE_LINE``` in the docs? I will disable this from day 1 in my code...

And one more thing: switching from ```#include <ppk_assert.h>``` to ```#include "ppk_assert.h"``` would be nice - so the folder doesn't have to be in the include path.

And one more thing : stuff like ```PPK_ASSERT_ACTION_BREAK``` from the documentation isn't present in the header - it has been moved to an enum.

Whops - I added quite a few things in this single "issue" :D

**Comment by gpakosz** [comment]
> what are PPK_ASSERT_FUNCSPEC and PPK_ASSERT_CALL for ?
> my guess is - if I want to build ppk_assert as a .dll?

That's correct.

> And a side question - would it be possible to remove as much as possible from the source file if PPK_ASSERT_ENABLED is 0? I don't want to rely on link-time optimizations to remove dead code.

When `PPK_ASSERT_ENABLED` is `0`, assertions ultimately expand to `PPK_ASSERT_UNUSED(expression)` which expends to `(void)(true ? (void)0 : ((void)(expression)))`. This is a known way to silence unused expression warnings and doesn't rely on the linker optimization capabilities.

> And one more note: Since C++11 local static variables are required to have synchronization added by the compiler for their initialization - so calling the function from multiple threads is safe. This may add A LOT of overhead if asserts are used on hot paths... Maybe this should be mentioned near PPK_ASSERT_DISABLE_IGNORE_LINE in the docs? I will disable this from day 1 in my code...

As `README.md` states:
> - `PPK_ASSERT_DISABLE_IGNORE_LINE`: disables the injection of a `static bool`
  variable used to keep track whether the assertion should be ignored for the
  remaining lifetime of the program.

So yes, use `#define PPK_ASSERT_DISABLE_IGNORE_LINE` if you're concerned about the overhead of thread safe initialization of local static variables.

> And one more thing: switching from #include <ppk_assert.h> to #include "ppk_assert.h" would be nice - so the folder doesn't have to be in the include path.

Are you referring to the way `ppk_assert.cpp` includes `ppk_assert.h` ? Because in the general case `ppk_assert.h` needs to be in the include path when included from **your** source files anyways.

> And one more thing : stuff like PPK_ASSERT_ACTION_BREAK from the documentation isn't present in the header - it has been moved to an enum.

Good catch, I'll update `README.md` accordingly

**Comment by onqtam** [comment]
> When PPK_ASSERT_ENABLED is 0, assertions ultimately expand to PPK_ASSERT_UNUSED(expression) which expends to (void)(true ? (void)0 : ((void)(expression))). This is a known way to silence unused expression warnings and doesn't rely on the linker optimization capabilities.

I was referring to the contents of ppk_assert.cpp

> Are you referring to the way ppk_assert.cpp includes ppk_assert.h ? Because in the general case ppk_assert.h needs to be in the include path when included from your source files anyways.

I like to include files with a folder too - like this: ```#include <ppk_assert/ppk_assert.h>``` - for the rare occasions when header names clash (will not happen with "ppk_" but its a good convention to not allow including the header directly...

**Comment by gpakosz** [comment]
> When PPK_ASSERT_ENABLED is 0, assertions ultimately expand to PPK_ASSERT_UNUSED(expression) which expends to (void)(true ? (void)0 : ((void)(expression))). >This is a known way to silence unused expression warnings and doesn't rely on the linker optimization capabilities.

>I was referring to the contents of ppk_assert.cpp

Well no. That's not how it works. You're supposed to be able to include `ppk_assert.h` multiple times from the same compilation units with different values for `PPK_ASSERT_ENABLED`. In that respect, `PPK_ASSERT_ENABLED` is not global.

**Comment by gpakosz** [comment]
Are we good?

**Comment by onqtam** [comment]
yes

**Comment by gpakosz** [comment]
I'll close the issue then. Thanks.
